version: "2.3"
services:
  pytorch_ws:
    image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
    network_mode: host
    ipc: host
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../:/home/user/Documents/pytorch_ws
    privileged: true
    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    command: bash -c "source /opt/ros/humble/setup.bash && rviz2"
    working_dir: /home/user/Documents/pytorch_ws